# spring:
#  profiles:
#    active: native
#  cloud:
#    client.hostname: ${spring.cloud.client.ip-address:localhost}
#    config:
#      override-system-properties: false
#      server:
#        native:
#          search-locations:
#            config/,
#            config/client-config-first,
#            config/client-discovery-first
#      bus:
#        enabled: true
#        refresh:
#         enabled: true
#      kafka:
#        bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}
server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: config-server
  cloud:
    client.hostname: ${spring.cloud.client.ip-address:localhost}
    config:
      override-system-properties: false
      server:
        git:
          uri: https://gitlab.com/pavitra14/spring-cloud-config.git
          skipSslValidation: true
          clone-on-start: true
          force-pull: true
          refreshRate: 5
    bus:
      enabled: true
    kafka:
      bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}