server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    client.hostname: ${spring.cloud.client.ip-address:localhost}
    config:
      override-system-properties: false
      server:
        git:
          uri: https://github.com/pavitra14/spring-cloud-config.git
          clone-on-start: true
          search-paths:
            config/,
            config/client-config-first,
            config/client-discovery-first
          username: pavitra14
    bus:
      enabled: true
    kafka:
      bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}